# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get install libegl1-mesa
        sudo apt-get install xclip
        sudo apt-get install gdb
        pip install coverage
        sudo apt-get install libxkbcommon-x11-0
        sudo apt-get install libxcb-icccm4
        sudo apt-get install libxcb-image0
        pip install coverage-badge
        sudo apt-get install xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
        export LD_LIBRARY_PATH=/usr/lib
    - name: Run tests
      env:
        QT_DEBUG_PLUGINS: 1
        DISPLAY: ':99.0'
      run: |
        xvfb-run --auto-servernum coverage run --source=pypgpeed -m unittest discover -s tests
        coverage report -m > ${{github.workspace}}/tests/coverage.txt
        coverage-badge -o ${{github.workspace}}/assets/coverage.svg
