# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get install libegl1-mesa
        sudo apt-get install xclip
        sudo apt-get install gdb
        export LD_LIBRARY_PATH=/usr/lib
    - name: Run tests
      env:
        QT_DEBUG_PLUGINS: 1
      run: |
        sudo xvfb-run --auto-servernum python -m unittest discover -s tests

